### PR TITLE
ROS-389 [rolling/humble/iron/jazzy]: replay-improvments-and-fixes

### LINKED ISSUE #389: replay_pcap is not working with cyclone_dds.
> **IMPORTANT**  
> Before reporting a new bug make sure you have:
> - [x] Checked existing issues https://github.com/ouster-lidar/ouster-ros/issues
> - [x] Checked existing discussions https://github.com/ouster-lidar/ouster-ros/discussions
> - [x] Checked ouster community https://community.ouster.com/
> If you couldn't find relevant information and you think this is rather a driver 
> problem then proceed with bug reporting.

**Describe the bug**
The ouster_pcap node is not working with CycloneDDS. However, it works fine when the DDS is set to default.

**To Reproduce**
1. Setting the DDS: 
`export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp`
2. compile the project workspace:
`colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_PCAP=ON --packages-select ouster_sensor_msgs ouster_ros`
3. ros launch ouster_ros sensor or replay:
`ros2 launch ouster_ros replay_pcap.launch.xml pcap_file:=/workspace/pcaps/2024099_1400_OS-1-128_122421001099.pcap metadata:=/workspace/pcaps/2024099_1400_OS-1-128_122421001099.json`
4. The Issue 
image

5. Setting default DDS:
`export RMW_IMPLEMENTATION=''`
6. ros launch ouster_ros sensor or replay:
`ros2 launch ouster_ros  replay_pcap.launch.xml pcap_file:=/root/ros2_bags/pcaps/2024099_1400_OS-1-128_122421001099.pcap metadata:=/root/ros2_bags/pcaps/2024099_1400_OS-1-128_122421001099.json`
7. Working successfully: 
image

**Platform (please complete the following information):**
- Ouster Sensor: OS-1
- ROS distro: humble
- Operating System: Linux 22.04
- Docker Environment: Yes
- Machine Architecture: x64
- git commit hash (ros2-v0.13.2).

### PR DESCRIPTION
**Pull request by Samahu**
## Related Issues & PRs
- related: #392
- resolves: #153
- resolves #389
- integrates: #330

## Summary of Changes
* Remap `/metadata` topic
* Support **loop** capability in pcap replay
* Add `play_delay` to regular replay and pcap replay
* Expose `play_rate` for the bag file replay
* Added a parameter `pub_static_tf` to disable tf tansforms broadcast 

## Validation
* Test the newly exposed flags for `replay_pcap`
```bash
ros2 launch ouster_ros replay_pcap.launch.xml pcap_file:=<...> json_file:=<...> loop:=true play_delay:=10
```
* Test the newly exposed flags for bag `replay`
```bash
ros2 launch ouster_ros replay_pcap.launch.xml bag_file:=<...> loop:=true play_delay:=10 play_rate:=1.5
```
* Test that setting `pub_static_tf` to `false` disables the publish of sensor tf transforms

### CODE REVIEW

File: ouster-ros/src/os_sensor_node_base.cpp [hunk 1]
```diff
@@ -74,4 +82,73 @@ bool OusterSensorNodeBase::write_text_to_file(const std::string& file_path,
...
+        case lifecycle_msgs::msg::Transition::TRANSITION_CREATE:
+            return "create"s;
+        case lifecycle_msgs::msg::Transition::TRANSITION_CONFIGURE:
+            return "configure"s;
+        case lifecycle_msgs::msg::Transition::TRANSITION_CLEANUP:
+            return "cleanup"s;
+        case lifecycle_msgs::msg::Transition::TRANSITION_ACTIVATE:
+            return "activate";
+        case lifecycle_msgs::msg::Transition::TRANSITION_DEACTIVATE:
+            return "deactivate"s;
```
Comment (matthew-lidar) [inline ouster-ros/src/os_sensor_node_base.cpp:96]: Why the random usage of s?

**Review by matthew-lidar — APPROVED** [review]

File: ouster-ros/src/os_sensor_node_base.cpp (hunk 1 above)
Comment (Samahu) [reply ouster-ros/src/os_sensor_node_base.cpp:96]: I think i am missing the `s` on "activate", this is syntactic sugar for string{""};
